### ISSUE TITLE
green badge

### ISSUE THREAD

**Issue by arhimede** [dotkernel/dot-user-agent-sniffer#14]
https://insight.symfony.com/projects/2e87cb23-ba35-4bef-a576-f9cb3a989ee9

[![SymfonyInsight](https://insight.symfony.com/projects/2e87cb23-ba35-4bef-a576-f9cb3a989ee9/big.svg)](https://insight.symfony.com/projects/2e87cb23-ba35-4bef-a576-f9cb3a989ee9)

**Comment by alexmerlin** [comment]
Fixed in #13
