### ISSUE TITLE
processing time

### ISSUE THREAD

**Issue by kakapiciu** [dotkernel/dot-user-agent-sniffer#4]
getting device information using 
return $this->deviceService->getDetails($userAgent);
taske @ 0.39 - 0.83 s
on development server

**Comment by alexmerlin** [comment]
Just benchmarked on my local machine using a batch of 71 useragents, processing times look fine. See the results:
* min: 0.002s
* max: 0.276s
* avg: 0.007s
* total: 0.543s

One thing I noticed, though: Calling UserAgentSniffer with a 'weird' user agent will throw an error:
`$device = $this->deviceService->getDetails($userAgent);`
> ErrorException raised in file vendor/dotkernel/dot-user-agent-sniffer/src/Data/ClientData.php line 124:
> Message: Undefined index: engine

But, this is a different situation, I just opened [an issue](https://github.com/dotkernel/dot-user-agent-sniffer/issues/5) for it.

**Comment by alexmerlin** [comment]
@kakapiciu Is this issue still relevant?

**Comment by kakapiciu** [comment]
@alexmerlin not anymore
after specific changes on project times went back to normal
